{{- if .Values.ingress.domain }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
  annotations:
#    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "{{ .Values.serviceName }}.{{ .Values.ingress.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: 80
  {{- if .Values.ingress.url }}
  - host: {{ .Values.ingress.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: 8080
  {{- end }}
{{- end }}
